# Generated by Django 2.0.5 on 2019-05-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(max_length=30)),
                ('tagline', models.CharField(max_length=30)),
                ('carModel', models.CharField(max_length=30)),
                ('mileage', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('horsepower', models.CharField(max_length=30)),
                ('propellant', models.CharField(max_length=30)),
            ],
        ),
    ]
