# Generated by Django 2.0.5 on 2019-05-03 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_showroom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='car',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='Car.Car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='carModel',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacture',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='propellant',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='tagline',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='name',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='registrationNumber',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='empty', max_length=30),
        ),
    ]
