# Generated by Django 2.0.5 on 2019-05-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_auto_20190503_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='logoType',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
