# Generated by Django 2.0.5 on 2019-05-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_auto_20190503_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='logoType',
            field=models.CharField(default='empty', max_length=30),
        ),
    ]
