# Generated by Django 2.0.5 on 2019-05-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0006_user_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.ShowRoom'),
        ),
    ]
