# Generated by Django 2.0.5 on 2019-05-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0007_auto_20190503_1017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ShowRoomOwner',
        ),
    ]
