# Generated by Django 2.0.5 on 2019-05-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0011_auto_20190503_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carModel',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacture',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='propellant',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='tagline',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='logoType',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='showroomowner',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='showroomowner',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='showroomowner',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
