# Generated by Django 2.1.1 on 2019-05-05 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0012_auto_20190503_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAssignToShowRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShowRoomOwnerAssignToShowRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='showroom',
        ),
        migrations.RemoveField(
            model_name='showroom',
            name='owner',
        ),
        migrations.AddField(
            model_name='showroomownerassigntoshowroom',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.ShowRoom'),
        ),
        migrations.AddField(
            model_name='showroomownerassigntoshowroom',
            name='showroomOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.ShowRoomOwner'),
        ),
        migrations.AddField(
            model_name='carassigntoshowroom',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.Car'),
        ),
        migrations.AddField(
            model_name='carassigntoshowroom',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.ShowRoom'),
        ),
    ]
