# Generated by Django 2.0.5 on 2019-05-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0013_auto_20190505_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carassigntoshowroom',
            old_name='car',
            new_name='Car',
        ),
    ]
