# Generated by Django 2.0.5 on 2019-05-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0014_auto_20190506_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carassigntoshowroom',
            old_name='Car',
            new_name='car',
        ),
    ]
