# Generated by Django 2.0.5 on 2019-05-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0015_auto_20190506_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='contactInfo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
