# Generated by Django 2.0.5 on 2019-05-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0016_showroom_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='file',
            field=models.FileField(default=-0.1, upload_to=''),
            preserve_default=False,
        ),
    ]
