# Generated by Django 2.0.5 on 2019-05-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0017_car_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='Car',
        ),
        migrations.AlterModelTable(
            name='carassigntoshowroom',
            table='CarAssignToShowRoom',
        ),
        migrations.AlterModelTable(
            name='showroom',
            table='ShowRoom',
        ),
        migrations.AlterModelTable(
            name='showroomowner',
            table='ShowRoomOwner',
        ),
        migrations.AlterModelTable(
            name='showroomownerassigntoshowroom',
            table='ShowRoomOwnerAssignToShowRoom',
        ),
    ]
