# Generated by Django 2.0.5 on 2019-05-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0017_car_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='carModel',
            new_name='car_model',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='horsepower',
            new_name='horse_power',
        ),
        migrations.RenameField(
            model_name='showroom',
            old_name='contactInfo',
            new_name='contact_info',
        ),
        migrations.RenameField(
            model_name='showroom',
            old_name='logoType',
            new_name='logo_type',
        ),
        migrations.RenameField(
            model_name='showroom',
            old_name='registrationNumber',
            new_name='registration_number',
        ),
        migrations.RenameField(
            model_name='showroomownerassigntoshowroom',
            old_name='showroomOwner',
            new_name='showroom_owner',
        ),
    ]
