# Generated by Django 2.0.5 on 2019-05-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0018_auto_20190513_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showroom',
            old_name='contact_info',
            new_name='contactInfo',
        ),
        migrations.RenameField(
            model_name='showroom',
            old_name='logo_type',
            new_name='logoType',
        ),
    ]
