# Generated by Django 2.0.5 on 2019-05-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0019_auto_20190513_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showroom',
            old_name='contactInfo',
            new_name='contact_info',
        ),
        migrations.RenameField(
            model_name='showroom',
            old_name='logoType',
            new_name='logo_type',
        ),
    ]
