# Generated by Django 2.0.5 on 2019-05-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0020_auto_20190513_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
