# Generated by Django 2.0.5 on 2019-05-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0021_auto_20190513_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.IntegerField(choices=[(0, 'Sold'), (1, 'In Stock')], default=0),
        ),
    ]
