# Generated by Django 2.0.5 on 2019-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0022_auto_20190513_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'Automatic')], default=0),
        ),
    ]
