# Generated by Django 2.2.1 on 2019-05-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0024_manufactor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufactorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('car_type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
