# Generated by Django 2.0.5 on 2019-05-16 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0025_auto_20190513_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('car', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Car.Car')),
            ],
        ),
    ]
