# Generated by Django 2.0.5 on 2019-05-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0026_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='file',
        ),
    ]
