# Generated by Django 2.0.5 on 2019-05-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0029_auto_20190516_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufactor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='manufactor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='manufactormodel',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='manufactormodel',
            name='name',
        ),
    ]
