# Generated by Django 2.0.5 on 2019-05-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0030_auto_20190521_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacture',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='propellant',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='tagline',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='contact_info',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='logo_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='registration_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='showroomowner',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='showroomowner',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='showroomowner',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
